### ISSUE TITLE
getting this error

### ISSUE THREAD

**Issue by AKGamingYT0** [elixirfw/elixir-scoreboard#2]
[script:ex-scoreboard] SCRIPT ERROR: @ex-scoreboard/sv_scoreboard.lua:91: bad argument #1 to 'sub' (string expected, got nil)
[script:ex-scoreboard] > HexIdToSteamId (@ex-scoreboard/sv_scoreboard.lua:91)
[script:ex-scoreboard] > handler (@ex-scoreboard/sv_scoreboard.lua:71)

getting this error

**Comment by elixirfw** [comment]
Update the Scoreboard with latest updates
